-- Per-org print template layouts (one active template per document type per org).

CREATE TABLE org_print_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id bigint NOT NULL REFERENCES org_settings (id),
  name text NOT NULL,
  document_type varchar(50) NOT NULL,
  context varchar(20) NOT NULL CHECK (context IN ('task', 'report')),
  template jsonb NOT NULL,
  content_hash varchar(64) NOT NULL,
  surfaces jsonb NOT NULL DEFAULT '{}',
  persist boolean NOT NULL DEFAULT false,
  requires_status varchar(50),
  sort_order integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, document_type)
);

CREATE INDEX org_print_templates_org_id_idx ON org_print_templates (org_id);
CREATE INDEX org_print_templates_document_type_idx ON org_print_templates (document_type);
