-- Org-configurable task attachment types (TATs) + optional link from task_attachments.

BEGIN;

CREATE TABLE org_attachment_type_defs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(100) NOT NULL,
  label varchar(100) NOT NULL,
  allowed_mime_categories jsonb NOT NULL DEFAULT '["image","video","pdf","other"]'::jsonb,
  show_when jsonb,
  sort_order int NOT NULL DEFAULT 0,
  retired_at timestamptz
);

CREATE UNIQUE INDEX org_attachment_type_defs_active_slug_idx
  ON org_attachment_type_defs (lower(slug))
  WHERE retired_at IS NULL;

CREATE INDEX org_attachment_type_defs_sort_idx
  ON org_attachment_type_defs (sort_order ASC, id ASC)
  WHERE retired_at IS NULL;

ALTER TABLE task_attachments
  ADD COLUMN attachment_type_id bigint REFERENCES org_attachment_type_defs (id) ON DELETE SET NULL;

CREATE INDEX task_attachments_type_idx ON task_attachments (attachment_type_id);

COMMIT;
