version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - type:chore
      - area:infra
    commit-message:
      prefix: chore
      include: scope
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      tiptap:
        patterns:
          - "@tiptap/*"
      capacitor:
        patterns:
          - "@capacitor/*"
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      msal:
        patterns:
          - "@azure/msal-*"
