/**
 * Delivery docket PDF — shared by the API and public-tracking paths.
 * Layout: docs/pdf-delivery-docket.md
 */

import PDFDocument from "pdfkit";
import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getPool } from "./db.mjs";
import { getObjectBuffer } from "./storage.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const LABEL_WIDTH = 110;
const MARGIN = 50;
const PAGE_WIDTH = 612; // US Letter
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LOGO_PATH = path.join(root, "public", "logo-qcd.png");
const LOGO_HEIGHT = 42;
const LOGO_WIDTH = LOGO_HEIGHT * (399 / 158); // QCD wordmark (public/logo-qcd.png)
const DOCUMENT_LAYOUT_VERSION = "v4";
const DOCKET_KIND = "delivery_docket";
const PROOF_OF_COMPLETION_KIND = "proof_of_completion";

/** Stored documents from older layouts are regenerated instead of served. */
export const CURRENT_DOCUMENT_STORAGE_PREFIX = `documents/${DOCUMENT_LAYOUT_VERSION}/`;

const GRID_COLUMNS = 3;
const GRID_GUTTER = 12;
const GRID_CAPTION_HEIGHT = 11;
const GRID_CELL_GAP = 10;
const GRID_FOOTER_RESERVE = 28;
/** Name / Signature / Date underline row + padding above footer. */
const SIGNATURE_BLOCK_HEIGHT = 36;
/** Gap between the last attachment row and the signature lines. */
const ATTACHMENT_TO_SIGNATURE_GAP = 8;

function companyName() {
  return (process.env.COMPANY_NAME ?? "Quick Change Display").trim() || "Quick Change Display";
}

/** Normalize Windows/Wodely line endings so CR is not drawn as a glyph (Ð). */
function normalizeText(value) {
  return String(value).replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

/** Strip HTML from rich task descriptions for PDF plain text. */
function htmlToPlainText(value) {
  if (value == null) return "";
  const raw = String(value).trim();
  if (!raw) return "";
  if (!/<[a-z][\s\S]*>/i.test(raw)) {
    return normalizeText(raw).replace(/\s+/g, " ").trim();
  }
  const withBreaks = raw
    .replace(/<\s*br\s*\/?\s*>/gi, "\n")
    .replace(/<\/\s*(p|div|h[1-6]|li|tr)\s*>/gi, "\n")
    .replace(/<\s*li[^>]*>/gi, "• ");
  const stripped = withBreaks.replace(/<[^>]+>/g, "");
  return normalizeText(stripped)
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function display(value) {
  if (value == null || String(value).trim() === "") return "n/a";
  return normalizeText(value);
}

function displayTaskDesc(value) {
  const plain = htmlToPlainText(value);
  if (!plain) return "n/a";
  return plain;
}

/** Jul 15 2026 01:09 PM */
function formatBodyDate(iso) {
  if (!iso) return "n/a";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "n/a";
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  let hours = d.getHours();
  const minutes = String(d.getMinutes()).padStart(2, "0");
  const ampm = hours >= 12 ? "PM" : "AM";
  hours = hours % 12 || 12;
  return `${months[d.getMonth()]} ${d.getDate()} ${d.getFullYear()} ${String(hours).padStart(2, "0")}:${minutes} ${ampm}`;
}

/** 2026-07-15 14:11 */
function formatFooterDate(date = new Date()) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const h = String(date.getHours()).padStart(2, "0");
  const min = String(date.getMinutes()).padStart(2, "0");
  return `${y}-${m}-${day} ${h}:${min}`;
}

function drawRow(doc, label, value, y) {
  const x = MARGIN;
  doc.font("Helvetica").fontSize(10).fillColor("#333333");
  doc.text(label, x, y, { width: LABEL_WIDTH, lineBreak: false });
  const valueX = x + LABEL_WIDTH;
  const valueWidth = CONTENT_WIDTH - LABEL_WIDTH;
  doc.font("Helvetica").fontSize(10).fillColor("#000000");
  doc.text(display(value), valueX, y, { width: valueWidth });
  return doc.y + 4;
}

function drawSectionTitle(doc, title, y) {
  doc.moveDown(0.4);
  const top = Math.max(y, doc.y);
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#000000");
  doc.text(title, MARGIN, top, { width: CONTENT_WIDTH });
  return doc.y + 8;
}

function drawUnderlineField(doc, label, width, x, y) {
  doc.font("Helvetica").fontSize(10).fillColor("#333333");
  doc.text(label, x, y, { lineBreak: false });
  const labelW = doc.widthOfString(label) + 6;
  const lineY = y + 12;
  doc
    .moveTo(x + labelW, lineY)
    .lineTo(x + width, lineY)
    .strokeColor("#000000")
    .lineWidth(0.5)
    .stroke();
}

function drawFooter(doc, company, pageNumber, pageCount) {
  const footerY = doc.page.height - MARGIN - 12;
  const generated = `Generated by ${display(company)} on ${formatFooterDate()}`;
  doc.font("Helvetica").fontSize(8).fillColor("#555555");
  doc.text(generated, MARGIN, footerY, {
    width: CONTENT_WIDTH - 40,
    lineBreak: false,
  });
  doc.text(`${pageNumber} / ${pageCount}`, MARGIN, footerY, {
    width: CONTENT_WIDTH,
    align: "right",
  });
}

function attachmentGridMetrics() {
  const cellWidth =
    (CONTENT_WIDTH - GRID_GUTTER * (GRID_COLUMNS - 1)) / GRID_COLUMNS;
  const imageHeight = Math.round(cellWidth * 0.75);
  const cellHeight = imageHeight + GRID_CAPTION_HEIGHT + GRID_CELL_GAP;
  return { cellWidth, imageHeight, cellHeight };
}

/**
 * Pre-compute page count when image thumbnails sit inline before signatures.
 * @param {number} pageHeight
 * @param {number} startY
 * @param {number} imageCount
 */
function planInlineAttachments(pageHeight, startY, imageCount) {
  const { cellWidth, imageHeight, cellHeight } = attachmentGridMetrics();
  const bottom = pageHeight - MARGIN - GRID_FOOTER_RESERVE;

  let y = startY;
  let pageCount = 1;
  let remaining = imageCount;

  while (remaining > 0) {
    const rowsFit = Math.max(0, Math.floor((bottom - y) / cellHeight));
    const cellsFit = rowsFit * GRID_COLUMNS;
    if (cellsFit === 0) {
      pageCount += 1;
      y = MARGIN;
      continue;
    }
    const placed = Math.min(remaining, cellsFit);
    y += Math.ceil(placed / GRID_COLUMNS) * cellHeight;
    remaining -= placed;
    if (remaining > 0) {
      pageCount += 1;
      y = MARGIN;
    }
  }

  const afterImagesY =
    imageCount > 0 ? y + ATTACHMENT_TO_SIGNATURE_GAP : y;
  if (afterImagesY + SIGNATURE_BLOCK_HEIGHT > bottom) {
    pageCount += 1;
  }

  return { cellWidth, imageHeight, cellHeight, pageCount };
}

/**
 * Draw unlabeled attachment thumbnails starting at `startY`.
 * Adds pages as needed; returns Y after the last row on the current page.
 * @param {PDFKit.PDFDocument} doc
 * @param {Array<{ buffer: Buffer, fileName: string, caption: string | null }>} images
 * @param {number} startY
 * @param {{ cellWidth: number, imageHeight: number, cellHeight: number }} grid
 * @param {() => void} onPageBreak finish current page footer and add a new page
 */
function drawInlineAttachments(doc, images, startY, grid, onPageBreak) {
  if (images.length === 0) return startY;

  const bottom = doc.page.height - MARGIN - GRID_FOOTER_RESERVE;
  let y = startY;
  let col = 0;

  for (const attachment of images) {
    if (col === 0 && y + grid.cellHeight > bottom) {
      onPageBreak();
      y = MARGIN;
    }

    const x = MARGIN + col * (grid.cellWidth + GRID_GUTTER);

    doc
      .rect(x, y, grid.cellWidth, grid.imageHeight)
      .strokeColor("#dddddd")
      .lineWidth(0.5)
      .stroke();
    doc.image(attachment.buffer, x + 1, y + 1, {
      fit: [grid.cellWidth - 2, grid.imageHeight - 2],
      align: "center",
      valign: "center",
    });

    const label = attachment.caption
      ? `${attachment.fileName} — ${attachment.caption}`
      : attachment.fileName;
    doc.font("Helvetica").fontSize(7).fillColor("#555555");
    doc.text(display(label), x, y + grid.imageHeight + 3, {
      width: grid.cellWidth,
      height: GRID_CAPTION_HEIGHT,
      ellipsis: true,
      lineBreak: false,
    });

    col += 1;
    if (col >= GRID_COLUMNS) {
      col = 0;
      y += grid.cellHeight;
    }
  }

  if (col !== 0) {
    y += grid.cellHeight;
  }

  return y;
}

/**
 * Download and normalize every image attachment for reliable PDFKit rendering.
 * PDFs and all other non-image attachments are excluded.
 * @param {number} taskId
 */
async function loadTaskImageAttachments(taskId) {
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT storage_key, file_name, caption
     FROM task_attachments
     WHERE task_id = $1
       AND lower(mime_type) LIKE 'image/%'
     ORDER BY created_at ASC, id ASC`,
    [taskId],
  );

  return Promise.all(
    rows.map(async (row) => {
      const source = await getObjectBuffer(String(row.storage_key));
      const buffer = await sharp(source)
        .autoOrient()
        .resize({ width: 900, height: 900, fit: "inside", withoutEnlargement: true })
        .jpeg({ quality: 82, mozjpeg: true })
        .toBuffer();
      return {
        buffer,
        fileName: row.file_name ? String(row.file_name) : "Image attachment",
        caption: row.caption ? String(row.caption) : null,
      };
    }),
  );
}

/**
 * Map API/DB task detail → docket fixture shape.
 * @param {Record<string, unknown>} task
 */
export function taskToDocketInput(task) {
  const contacts = Array.isArray(task.contacts) ? task.contacts : [];
  const poc =
    contacts.find((c) => c && c.isPoc) ??
    contacts[0] ??
    null;

  const crewMembers = Array.isArray(task.crewMembers) ? task.crewMembers : [];
  const crewName =
    crewMembers
      .map((m) => (m && m.displayName ? String(m.displayName).trim() : ""))
      .filter(Boolean)
      .join(", ") ||
    (typeof task.crewName === "string" ? task.crewName : null);

  const completionNotesByName =
    typeof task.completionNotesByName === "string" &&
    task.completionNotesByName.trim()
      ? task.completionNotesByName.trim()
      : null;

  return {
    taskId: task.id,
    companyName: companyName(),
    completedAt: task.completedAt ?? null,
    destinationAddressName: task.destinationAddressName ?? null,
    contactName: poc?.name ?? null,
    destinationAddress: task.destinationAddress ?? null,
    destinationBuilding: task.destinationBuilding ?? null,
    contactEmail: poc?.email ?? null,
    contactPhone: poc?.phone ?? null,
    externalKey: task.externalKey ?? null,
    taskType: task.taskType ?? null,
    crewName,
    status: task.status ?? null,
    createdAt: task.createdAt ?? null,
    taskDesc: task.description ?? task.taskDesc ?? null,
    receivedByName: completionNotesByName,
    completedNotes: task.completedNotes ?? null,
    imageAttachments: Array.isArray(task.imageAttachments)
      ? task.imageAttachments
      : [],
  };
}

/**
 * @param {Record<string, unknown>} docket
 * @returns {Promise<Buffer>}
 */
function renderCompletionDocumentBuffer(
  docket,
  {
    title = "Delivery Docket",
    completionSectionTitle = "POD",
    completionNameLabel = "Received by",
  } = {},
) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
      info: {
        Title: `${title} ${docket.taskId}`,
        Author: String(docket.companyName ?? companyName()),
      },
    });

    /** @type {Buffer[]} */
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    let y = MARGIN;

    doc.image(LOGO_PATH, MARGIN, y, {
      width: LOGO_WIDTH,
      height: LOGO_HEIGHT,
    });

    doc.font("Helvetica-Bold").fontSize(18).fillColor("#000000");
    const titleH = doc.currentLineHeight();
    doc.text(title, MARGIN, y + (LOGO_HEIGHT - titleH) / 2, {
      width: CONTENT_WIDTH,
      align: "right",
      lineBreak: false,
    });
    y = MARGIN + LOGO_HEIGHT + 14;

    doc.font("Helvetica").fontSize(10).fillColor("#000000");
    const idLine = `Task ID: ${display(docket.taskId)}    External ID: ${display(docket.externalKey)}`;
    doc.text(idLine, MARGIN, y, {
      width: CONTENT_WIDTH / 2,
      lineBreak: false,
    });
    if (docket.completedAt) {
      doc.text(`Completed on ${formatBodyDate(docket.completedAt)}`, MARGIN, y, {
        width: CONTENT_WIDTH,
        align: "right",
      });
    }
    y = doc.y + 12;

    y = drawSectionTitle(doc, "Destination Location", y);
    y = drawRow(doc, "Location", docket.destinationAddressName, y);
    y = drawRow(doc, "Contact", docket.contactName, y);
    y = drawRow(doc, "Address", docket.destinationAddress, y);
    y = drawRow(doc, "Building", docket.destinationBuilding, y);
    y = drawRow(doc, "Email", docket.contactEmail, y);
    y = drawRow(doc, "Phone", docket.contactPhone, y);
    y += 8;

    y = drawSectionTitle(doc, "Summary", y);
    y = drawRow(doc, "Type", docket.taskType, y);
    y = drawRow(doc, "Crew", docket.crewName, y);
    y = drawRow(doc, "Status", docket.status, y);
    y = drawRow(doc, "Created", formatBodyDate(docket.createdAt), y);
    y += 8;

    y = drawSectionTitle(doc, "Description", y);
    doc.font("Helvetica").fontSize(10).fillColor("#000000");
    doc.text(displayTaskDesc(docket.taskDesc), MARGIN, y, { width: CONTENT_WIDTH });
    y = doc.y + 12;

    y = drawSectionTitle(doc, completionSectionTitle, y);
    const receivedParts = [];
    if (docket.receivedByName) receivedParts.push(String(docket.receivedByName));
    if (docket.completedAt) receivedParts.push(formatBodyDate(docket.completedAt));
    const receivedBy =
      receivedParts.length > 0 ? receivedParts.join(" , ") : null;
    y = drawRow(doc, completionNameLabel, receivedBy, y);
    y = drawRow(doc, "Notes", docket.completedNotes, y);
    y += 16;

    const images = Array.isArray(docket.imageAttachments)
      ? docket.imageAttachments
      : [];
    const layout = planInlineAttachments(
      doc.page.height,
      y,
      images.length,
    );
    const pageCount = layout.pageCount;

    let pageNumber = 1;
    const finishPage = () => {
      drawFooter(doc, docket.companyName, pageNumber, pageCount);
    };
    const startNextPage = () => {
      finishPage();
      doc.addPage();
      pageNumber += 1;
    };

    if (images.length > 0) {
      y = drawInlineAttachments(doc, images, y, layout, startNextPage);
      y += ATTACHMENT_TO_SIGNATURE_GAP;
    }

    const bottom = doc.page.height - MARGIN - GRID_FOOTER_RESERVE;
    if (y + SIGNATURE_BLOCK_HEIGHT > bottom) {
      startNextPage();
      y = MARGIN;
    }

    const colW = CONTENT_WIDTH / 3;
    drawUnderlineField(doc, "Name", colW - 12, MARGIN, y);
    drawUnderlineField(doc, "Signature", colW - 12, MARGIN + colW, y);
    drawUnderlineField(doc, "Date", colW - 12, MARGIN + colW * 2, y);
    finishPage();

    doc.end();
  });
}

/**
 * @param {Record<string, unknown>} docket
 * @returns {Promise<Buffer>}
 */
export function renderDeliveryDocketBuffer(docket) {
  return renderCompletionDocumentBuffer(docket);
}

/**
 * @param {Record<string, unknown>} docket
 * @returns {Promise<Buffer>}
 */
export function renderProofOfCompletionBuffer(docket) {
  return renderCompletionDocumentBuffer(docket, {
    title: "Proof of Completion",
    completionSectionTitle: "Completion",
    completionNameLabel: "Completed by",
  });
}

/**
 * @param {number} taskId
 */
export function deliveryDocketFileName(taskId) {
  const safeId = String(taskId).replace(/[^\w-]+/g, "_");
  return `delivery-docket-${safeId}.pdf`;
}

/**
 * @param {number} taskId
 */
export function deliveryDocketStorageKey(taskId) {
  return `documents/${DOCUMENT_LAYOUT_VERSION}/${deliveryDocketFileName(taskId)}`;
}

/**
 * @param {number} taskId
 */
export function proofOfCompletionFileName(taskId) {
  const safeId = String(taskId).replace(/[^\w-]+/g, "_");
  return `proof-of-completion-${safeId}.pdf`;
}

/**
 * @param {number} taskId
 */
export function proofOfCompletionStorageKey(taskId) {
  return `documents/${DOCUMENT_LAYOUT_VERSION}/${proofOfCompletionFileName(taskId)}`;
}

async function storeTaskDocument({
  taskId,
  kind,
  storageKey,
  fileName,
  buffer,
  generatedByUserId,
}) {
  const outPath = path.join(root, "storage", storageKey);
  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, buffer);

  const generatedBy =
    typeof generatedByUserId === "string" && generatedByUserId.trim()
      ? generatedByUserId.trim()
      : null;

  const pool = getPool();
  await pool.query(
    `INSERT INTO task_documents (
       task_id, kind, storage_key, file_name, generated_at, generated_by_user_id
     ) VALUES ($1, $2, $3, $4, now(), $5::uuid)
     ON CONFLICT (task_id, kind) DO UPDATE SET
       storage_key = EXCLUDED.storage_key,
       file_name = EXCLUDED.file_name,
       generated_at = EXCLUDED.generated_at,
       generated_by_user_id = EXCLUDED.generated_by_user_id`,
    [taskId, kind, storageKey, fileName, generatedBy],
  );

  return { buffer, fileName, storageKey, outPath };
}

/**
 * Generate PDF for a task, write under storage/documents, upsert task_documents.
 * @param {Record<string, unknown>} task API task detail
 * @param {{ generatedByUserId?: string | null }} [opts]
 */
export async function generateAndStoreDeliveryDocket(task, opts = {}) {
  const taskId = Number(task.id);
  if (!Number.isFinite(taskId)) {
    throw Object.assign(new Error("Invalid task id"), { status: 400 });
  }

  const imageAttachments = await loadTaskImageAttachments(taskId);
  const docket = taskToDocketInput({ ...task, imageAttachments });
  const fileName = deliveryDocketFileName(taskId);
  const storageKey = deliveryDocketStorageKey(taskId);
  const buf = await renderDeliveryDocketBuffer(docket);

  return storeTaskDocument({
    taskId,
    kind: DOCKET_KIND,
    storageKey,
    fileName,
    buffer: buf,
    generatedByUserId: opts.generatedByUserId,
  });
}

/**
 * Generate a proof of completion PDF, write it under storage/documents,
 * and upsert task_documents.
 * @param {Record<string, unknown>} task API task detail
 * @param {{ generatedByUserId?: string | null }} [opts]
 */
export async function generateAndStoreProofOfCompletion(task, opts = {}) {
  const taskId = Number(task.id);
  if (!Number.isFinite(taskId)) {
    throw Object.assign(new Error("Invalid task id"), { status: 400 });
  }
  if (String(task.status) !== "Completed") {
    throw Object.assign(
      new Error("Proof of completion is only available for completed tasks"),
      { status: 409 },
    );
  }

  const imageAttachments = await loadTaskImageAttachments(taskId);
  const docket = taskToDocketInput({ ...task, imageAttachments });
  const fileName = proofOfCompletionFileName(taskId);
  const storageKey = proofOfCompletionStorageKey(taskId);
  const buf = await renderProofOfCompletionBuffer(docket);

  return storeTaskDocument({
    taskId,
    kind: PROOF_OF_COMPLETION_KIND,
    storageKey,
    fileName,
    buffer: buf,
    generatedByUserId: opts.generatedByUserId,
  });
}
