/**
 * Shared US Letter PDF layout primitives for JSON document templates.
 */

export const LABEL_WIDTH = 110;
export const MARGIN = 50;
export const PAGE_WIDTH = 612;
export const PAGE_HEIGHT = 792;
export const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
export const LOGO_HEIGHT = 42;
export const LOGO_WIDTH = LOGO_HEIGHT;
export const INVOICE_GRAY = "#C0C0C0";
export const TITLE_BAR_HEIGHT = 26;
export const TABLE_ROW_HEIGHT = 22;
export const LINE_ROW_HEIGHT = 22;
export const TOTAL_AMOUNT_WIDTH = 104;

export const GRID_COLUMNS = 3;
export const GRID_GUTTER = 12;
export const GRID_CAPTION_HEIGHT = 11;
export const GRID_CELL_GAP = 10;
export const GRID_FOOTER_RESERVE = 28;
export const SIGNATURE_BLOCK_HEIGHT = 36;
export const ATTACHMENT_TO_SIGNATURE_GAP = 8;

/** Normalize Windows-style line endings so CR is not drawn as a glyph. */
export function normalizeText(value) {
  return String(value).replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

/** Strip HTML from rich task descriptions for PDF plain text. */
export function htmlToPlainText(value) {
  if (value == null) return "";
  const raw = String(value).trim();
  if (!raw) return "";
  if (!/<[a-z][\s\S]*>/i.test(raw)) {
    return normalizeText(raw).replace(/\s+/g, " ").trim();
  }
  const withBreaks = raw
    .replace(/<\s*br\s*\/?\s*>/gi, "\n")
    .replace(/<\/\s*(p|div|h[1-6]|li|tr)\s*>/gi, "\n")
    .replace(/<\s*li[^>]*>/gi, "• ");
  const stripped = withBreaks.replace(/<[^>]+>/g, "");
  return normalizeText(stripped)
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

export function display(value) {
  if (value == null || String(value).trim() === "") return "n/a";
  return normalizeText(value);
}

/** Fill-in fields stay blank when the tag is missing (do not print n/a). */
export function fillInText(value) {
  if (value == null) return "";
  const text = normalizeText(value).trim();
  if (!text || text === "n/a") return "";
  return text;
}

/** Jul 15 2026 01:09 PM */
export function formatBodyDate(iso) {
  if (!iso) return "n/a";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "n/a";
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  let hours = d.getHours();
  const minutes = String(d.getMinutes()).padStart(2, "0");
  const ampm = hours >= 12 ? "PM" : "AM";
  hours = hours % 12 || 12;
  return `${months[d.getMonth()]} ${d.getDate()} ${d.getFullYear()} ${String(hours).padStart(2, "0")}:${minutes} ${ampm}`;
}

/** 2026-07-15 14:11 */
export function formatFooterDate(date = new Date()) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const h = String(date.getHours()).padStart(2, "0");
  const min = String(date.getMinutes()).padStart(2, "0");
  return `${y}-${m}-${day} ${h}:${min}`;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {string} label
 * @param {unknown} value
 * @param {number} y
 */
export function drawRow(doc, label, value, y, x = MARGIN, width = CONTENT_WIDTH) {
  doc.font("Helvetica").fontSize(10).fillColor("#333333");
  doc.text(label, x, y, { width: LABEL_WIDTH, lineBreak: false });
  const valueX = x + LABEL_WIDTH;
  const valueWidth = width - LABEL_WIDTH;
  doc.font("Helvetica").fontSize(10).fillColor("#000000");
  doc.text(display(value), valueX, y, { width: valueWidth });
  return doc.y + 4;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 * @param {number} y
 */
export function drawSectionTitle(doc, title, y, x = MARGIN, width = CONTENT_WIDTH) {
  doc.moveDown(0.4);
  const top = Math.max(y, doc.y);
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#000000");
  doc.text(title, x, top, { width });
  return doc.y + 8;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {string} label
 * @param {number} width
 * @param {number} x
 * @param {number} y
 */
export function drawUnderlineField(doc, label, width, x, y) {
  doc.font("Helvetica").fontSize(10).fillColor("#333333");
  doc.text(label, x, y, { lineBreak: false });
  const labelW = doc.widthOfString(label) + 6;
  const lineY = y + 12;
  doc
    .moveTo(x + labelW, lineY)
    .lineTo(x + width, lineY)
    .strokeColor("#000000")
    .lineWidth(0.5)
    .stroke();
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {unknown} company
 * @param {number} pageNumber
 * @param {number} pageCount
 */
export function drawFooter(doc, company, pageNumber, pageCount) {
  const footerY = doc.page.height - MARGIN - 12;
  const generated = `Generated by ${display(company)} on ${formatFooterDate()}`;
  doc.font("Helvetica").fontSize(8).fillColor("#555555");
  doc.text(generated, MARGIN, footerY, {
    width: CONTENT_WIDTH - 40,
    lineBreak: false,
  });
  doc.text(`${pageNumber} / ${pageCount}`, MARGIN, footerY, {
    width: CONTENT_WIDTH,
    align: "right",
  });
}

export function attachmentGridMetrics() {
  const cellWidth =
    (CONTENT_WIDTH - GRID_GUTTER * (GRID_COLUMNS - 1)) / GRID_COLUMNS;
  const imageHeight = Math.round(cellWidth * 0.75);
  const cellHeight = imageHeight + GRID_CAPTION_HEIGHT + GRID_CELL_GAP;
  return { cellWidth, imageHeight, cellHeight };
}

/**
 * @param {number} pageHeight
 * @param {number} startY
 * @param {number} imageCount
 */
export function planInlineAttachments(pageHeight, startY, imageCount) {
  const { cellHeight } = attachmentGridMetrics();
  const bottom = pageHeight - MARGIN - GRID_FOOTER_RESERVE;

  let y = startY;
  let pageCount = 1;
  let remaining = imageCount;

  while (remaining > 0) {
    const rowsFit = Math.max(0, Math.floor((bottom - y) / cellHeight));
    const cellsFit = rowsFit * GRID_COLUMNS;
    if (cellsFit === 0) {
      pageCount += 1;
      y = MARGIN;
      continue;
    }
    const placed = Math.min(remaining, cellsFit);
    y += Math.ceil(placed / GRID_COLUMNS) * cellHeight;
    remaining -= placed;
    if (remaining > 0) {
      pageCount += 1;
      y = MARGIN;
    }
  }

  const afterImagesY =
    imageCount > 0 ? y + ATTACHMENT_TO_SIGNATURE_GAP : y;
  if (afterImagesY + SIGNATURE_BLOCK_HEIGHT > bottom) {
    pageCount += 1;
  }

  return { ...attachmentGridMetrics(), pageCount };
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {Array<{ buffer: Buffer, fileName: string, caption: string | null }>} images
 * @param {number} startY
 * @param {{ cellWidth: number, imageHeight: number, cellHeight: number }} grid
 * @param {() => void} onPageBreak
 */
export function drawInlineAttachments(doc, images, startY, grid, onPageBreak) {
  if (images.length === 0) return startY;

  const bottom = doc.page.height - MARGIN - GRID_FOOTER_RESERVE;
  let y = startY;
  let col = 0;

  for (const attachment of images) {
    if (col === 0 && y + grid.cellHeight > bottom) {
      onPageBreak();
      y = MARGIN;
    }

    const x = MARGIN + col * (grid.cellWidth + GRID_GUTTER);

    doc
      .rect(x, y, grid.cellWidth, grid.imageHeight)
      .strokeColor("#dddddd")
      .lineWidth(0.5)
      .stroke();
    doc.image(attachment.buffer, x + 1, y + 1, {
      fit: [grid.cellWidth - 2, grid.imageHeight - 2],
      align: "center",
      valign: "center",
    });

    const label = attachment.caption
      ? `${attachment.fileName} — ${attachment.caption}`
      : attachment.fileName;
    doc.font("Helvetica").fontSize(7).fillColor("#555555");
    doc.text(display(label), x, y + grid.imageHeight + 3, {
      width: grid.cellWidth,
      height: GRID_CAPTION_HEIGHT,
      ellipsis: true,
      lineBreak: false,
    });

    col += 1;
    if (col >= GRID_COLUMNS) {
      col = 0;
      y += grid.cellHeight;
    }
  }

  if (col !== 0) {
    y += grid.cellHeight;
  }

  return y;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} x
 * @param {number} y
 * @param {number} width
 */
export function drawHairline(doc, x, y, width) {
  doc.rect(x, y, width, 0.9).fillColor("#000000").fill();
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} inset
 */
export function drawPageBorder(doc, inset = 28) {
  doc
    .rect(inset, inset, PAGE_WIDTH - inset * 2, PAGE_HEIGHT - inset * 2)
    .strokeColor("#000000")
    .lineWidth(1)
    .stroke();
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {{ fill?: string, height?: number, size?: number }} [opts]
 */
export function drawTitleBar(doc, title, x, y, width, opts = {}) {
  const height = typeof opts.height === "number" ? opts.height : TITLE_BAR_HEIGHT;
  const fill = typeof opts.fill === "string" ? opts.fill : INVOICE_GRAY;
  const size = typeof opts.size === "number" ? opts.size : 20;
  doc.save();
  doc.rect(x, y, width, height).fillColor(fill).fill();
  doc.restore();
  doc.font("Helvetica-Bold").fontSize(size).fillColor("#000000");
  const textY = y + Math.max(4, (height - size) / 2 + 2);
  doc.text(title, x, textY, {
    width,
    align: "center",
    lineBreak: false,
  });
  return y + height;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {{ label?: string, caption?: string, value?: string, size?: number, bold?: boolean }} opts
 */
export function drawLabeledLine(doc, x, y, width, opts) {
  const label = typeof opts.label === "string" ? opts.label : "";
  const caption = typeof opts.caption === "string" ? opts.caption : "";
  const value = fillInText(opts.value);
  const size = typeof opts.size === "number" ? opts.size : 12;
  const font = opts.bold === false ? "Helvetica" : "Helvetica-Bold";
  const textY = y;
  let lineX = x;
  if (label) {
    doc.font(font).fontSize(size).fillColor("#000000");
    doc.text(label, x, textY, { lineBreak: false });
    lineX = x + doc.widthOfString(label) + 8;
  }
  const lineWidth = Math.max(24, x + width - lineX);
  const lineY = textY + size + 1;
  if (value) {
    doc.font("Helvetica").fontSize(size).fillColor("#000000");
    doc.text(value, lineX + 2, textY, {
      width: lineWidth - 4,
      lineBreak: false,
    });
  }
  drawHairline(doc, lineX, lineY, lineWidth);
  if (caption) {
    doc.font("Helvetica").fontSize(10).fillColor("#000000");
    doc.text(caption, lineX, lineY + 4, {
      width: lineWidth,
      lineBreak: false,
    });
    return lineY + 18;
  }
  return lineY + 8;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {number} lines
 * @param {string[]} [values]
 * @param {number} [rowHeight]
 */
export function drawLineStack(doc, x, y, width, lines, values = [], rowHeight = LINE_ROW_HEIGHT) {
  const count = Math.max(1, lines);
  let cursor = y;
  for (let i = 0; i < count; i++) {
    const value = fillInText(values[i]);
    const lineY = cursor + 12;
    if (value) {
      doc.font("Helvetica").fontSize(11).fillColor("#000000");
      doc.text(value, x + 2, cursor, {
        width: width - 4,
        lineBreak: false,
      });
    }
    drawHairline(doc, x, lineY, width);
    cursor += rowHeight;
  }
  return cursor;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {{ label: string, width?: number, align?: string }[]} columns
 * @param {{ rowCount?: number, rows?: string[][], headerFill?: string, rowHeight?: number }} [opts]
 */
export function drawTable(doc, x, y, width, columns, opts = {}) {
  const rowHeight =
    typeof opts.rowHeight === "number" ? opts.rowHeight : TABLE_ROW_HEIGHT;
  const headerFill =
    typeof opts.headerFill === "string" ? opts.headerFill : INVOICE_GRAY;
  const dataRows = Array.isArray(opts.rows) ? opts.rows : [];
  const rowCount = Math.max(
    typeof opts.rowCount === "number" ? opts.rowCount : dataRows.length,
    dataRows.length,
    1,
  );
  const specified = columns.reduce(
    (sum, col) => sum + (typeof col.width === "number" ? col.width : 0),
    0,
  );
  const autoCount = columns.filter((col) => typeof col.width !== "number").length;
  const autoWidth =
    autoCount > 0 ? Math.max(0, 1 - specified) / autoCount : 0;
  const colWidths = columns.map((col) => {
    const fraction = typeof col.width === "number" ? col.width : autoWidth;
    return width * fraction;
  });

  const headerH = rowHeight;
  doc.save();
  doc.rect(x, y, width, headerH).fillColor(headerFill).fill();
  doc.restore();

  let colX = x;
  columns.forEach((col, i) => {
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#000000");
    const pad = 4;
    doc.text(col.label, colX + pad, y + 6, {
      width: colWidths[i] - pad * 2,
      align: col.align === "right" || col.align === "center" ? col.align : "left",
      lineBreak: false,
    });
    colX += colWidths[i];
  });

  const tableBottom = y + headerH + rowCount * rowHeight;
  doc.save();
  doc.strokeColor("#000000").lineWidth(0.75);
  doc.rect(x, y, width, tableBottom - y).stroke();
  for (let r = 1; r <= rowCount; r++) {
    const rowY = y + headerH + r * rowHeight;
    doc.moveTo(x, rowY).lineTo(x + width, rowY).stroke();
  }
  doc.moveTo(x, y + headerH).lineTo(x + width, y + headerH).stroke();
  colX = x;
  for (let i = 0; i < colWidths.length - 1; i++) {
    colX += colWidths[i];
    doc.moveTo(colX, y).lineTo(colX, tableBottom).stroke();
  }
  doc.restore();

  dataRows.forEach((row, r) => {
    if (!Array.isArray(row)) return;
    let cellX = x;
    columns.forEach((col, c) => {
      const cell = fillInText(row[c]);
      if (cell) {
        doc.font("Helvetica").fontSize(10).fillColor("#000000");
        doc.text(cell, cellX + 4, y + headerH + r * rowHeight + 5, {
          width: colWidths[c] - 8,
          lineBreak: false,
        });
      }
      cellX += colWidths[c];
    });
  });

  return tableBottom;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {{ label: string, value?: string, bold?: boolean, box?: boolean }} opts
 */
export function drawTotalRow(doc, x, y, width, opts) {
  const amountWidth = Math.min(TOTAL_AMOUNT_WIDTH, width * 0.45);
  const labelWidth = Math.max(40, width - amountWidth - 8);
  const labelX = x;
  const amountX = x + width - amountWidth;
  const font = opts.bold ? "Helvetica-Bold" : "Helvetica";
  doc.font(font).fontSize(12).fillColor("#000000");
  doc.text(opts.label, labelX, y + 2, {
    width: labelWidth,
    align: "right",
    lineBreak: false,
  });
  const value = fillInText(opts.value);
  if (value) {
    doc.font("Helvetica").fontSize(12).fillColor("#000000");
    doc.text(value, amountX + 4, y + 2, {
      width: amountWidth - 8,
      lineBreak: false,
    });
  }
  if (opts.box) {
    doc
      .rect(amountX, y, amountWidth, 22)
      .strokeColor("#000000")
      .lineWidth(2)
      .stroke();
    return y + 26;
  }
  drawHairline(doc, amountX, y + 14, amountWidth);
  return y + LINE_ROW_HEIGHT;
}

/**
 * @param {PDFKit.PDFDocument} doc
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {string} [label]
 */
export function drawCutHere(doc, x, y, width, label = "Cut here") {
  const dashY = y + 8;
  doc.save();
  doc
    .strokeColor("#000000")
    .lineWidth(0.75)
    .dash(3, { space: 2 })
    .moveTo(x, dashY)
    .lineTo(x + width, dashY)
    .stroke()
    .undash();
  doc.restore();
  doc.font("Helvetica").fontSize(10).fillColor("#000000");
  doc.text(label, x, dashY + 4, {
    width,
    align: "center",
    lineBreak: false,
  });
  return dashY + 18;
}
