import { useEffect, useState } from 'react';
import { Group, Loader, Text } from '@mantine/core';
import { ChevronDown } from 'lucide-react';
import { documentKindLabel } from '../../shared/documentTypes.js';
import { getTaskHistory, type TaskHistoryEvent } from '../api/tasks';
import { formatShortName } from '../formatName';
import { RelativeTime } from './RelativeTime';
import { notifyError } from '../notify';

function kindLabel(kind: string | null, count = 1): string {
	if (!kind) return count === 1 ? 'Attachment' : 'Attachments';
	switch (kind) {
		case 'photo':
			return count === 1 ? 'Photo' : 'Photos';
		case 'signature':
			return count === 1 ? 'Signature' : 'Signatures';
		case 'document':
			return count === 1 ? 'Document' : 'Documents';
		case 'video':
			return count === 1 ? 'Video' : 'Videos';
		default:
			return documentKindLabel(kind, count);
	}
}

function eventTitle(event: TaskHistoryEvent): string {
	const who = event.actorName ? formatShortName(event.actorName) : null;

	switch (event.type) {
		case 'created':
			return who ? `Task created by ${who}` : 'Task created';
		case 'status_changed': {
			const from = event.fromStatus ?? '—';
			const to = event.toStatus ?? '—';
			return who
				? `Status ${from} → ${to} by ${who}`
				: `Status ${from} → ${to}`;
		}
		case 'crew_started':
		case 'crew_ended': {
			const action = event.type === 'crew_started' ? 'started' : 'ended';
			const base = who ? `${who} ${action}` : `Crew ${action}`;
			if (event.fromStatus && event.toStatus) {
				return `${base} · ${event.fromStatus} → ${event.toStatus}`;
			}
			if (event.toStatus) {
				return `${base} · → ${event.toStatus}`;
			}
			return base;
		}
		case 'cancelled': {
			const from = event.fromStatus;
			return from
				? `Cancelled (was ${from})`
				: who
					? `Cancelled by ${who}`
					: 'Cancelled';
		}
		case 'restored':
			return who
				? `Restored to ${event.toStatus ?? 'Undetermined'} by ${who}`
				: `Restored to ${event.toStatus ?? 'Undetermined'}`;
		case 'attachment_added': {
			const count =
				typeof event.count === 'number' && event.count > 1 ? event.count : 1;
			const label = kindLabel(event.detail, count);
			const subject = count > 1 ? `${count} ${label.toLowerCase()}` : label;
			return who ? `${subject} added by ${who}` : `${subject} added`;
		}
		case 'document_generated':
			return who
				? `${kindLabel(event.detail)} generated by ${who}`
				: `${kindLabel(event.detail)} generated`;
		case 'email_sent':
			return event.summary?.trim()
				? `Email: ${event.summary.trim()}`
				: 'Email sent';
		case 'note_added': {
			const outcome = event.toStatus === 'Failed' ? 'Failed note' : 'Completed note';
			return who ? `${outcome} by ${who}` : outcome;
		}
		default:
			return who ? `${event.type} by ${who}` : event.type;
	}
}

function eventBody(event: TaskHistoryEvent): string | null {
	if (event.type === 'note_added' || event.type === 'status_changed') {
		return event.summary?.trim() || null;
	}
	if (event.type === 'attachment_added') {
		// Batched uploads omit per-file names on purpose.
		if (typeof event.count === 'number' && event.count > 1) return null;
		const name = event.summary?.trim();
		if (name && name.toLowerCase() !== (event.detail ?? '').toLowerCase()) {
			return name;
		}
		return null;
	}
	if (event.type === 'document_generated') {
		const name = event.summary?.trim();
		if (name && name.toLowerCase() !== (event.detail ?? '').toLowerCase()) {
			return name;
		}
		return null;
	}
	if (event.type === 'email_sent') {
		return event.detail?.trim() || null;
	}
	if (event.type === 'crew_started' || event.type === 'crew_ended') {
		return event.summary?.trim() || null;
	}
	return event.detail?.trim() || event.summary?.trim() || null;
}

interface TaskHistoryProps {
	taskId: number;
	/** Remount / refetch when task activity changes (e.g. status). */
	refreshKey?: string | number;
	defaultExpanded?: boolean;
	className?: string;
}

export function TaskHistory({
	taskId,
	refreshKey,
	defaultExpanded = false,
	className,
}: TaskHistoryProps) {
	const [expanded, setExpanded] = useState(defaultExpanded);
	const [events, setEvents] = useState<TaskHistoryEvent[]>([]);
	const [loading, setLoading] = useState(false);
	const [loaded, setLoaded] = useState(false);

	useEffect(() => {
		setLoaded(false);
		setEvents([]);
	}, [taskId, refreshKey]);

	useEffect(() => {
		if (!expanded || loaded) return;

		const controller = new AbortController();
		setLoading(true);

		getTaskHistory(taskId, controller.signal)
			.then((next) => {
				if (!controller.signal.aborted) {
					setEvents(next);
					setLoaded(true);
				}
			})
			.catch((err: unknown) => {
				if (err instanceof DOMException && err.name === 'AbortError') return;
				notifyError(err instanceof Error ? err.message : 'Failed to load history');
			})
			.finally(() => {
				if (!controller.signal.aborted) setLoading(false);
			});

		return () => controller.abort();
	}, [expanded, loaded, taskId]);

	const countLabel = loaded ? ` (${events.length})` : '';

	return (
		<section
			className={
				[
					'task-view-attachments',
					'task-history',
					expanded ? '' : 'task-view-attachments--collapsed',
					className ?? '',
				]
					.filter(Boolean)
					.join(' ')
			}
			aria-label={`History${countLabel}`}
		>
			<button
				type='button'
				className='task-attachments-toggle'
				aria-expanded={expanded}
				onClick={() => setExpanded((prev) => !prev)}
			>
				<span className='task-attachments-toggle-label'>
					History{countLabel}
				</span>
				<ChevronDown
					size={18}
					strokeWidth={2}
					aria-hidden
					className={
						expanded
							? 'task-attachments-toggle-icon'
							: 'task-attachments-toggle-icon task-attachments-toggle-icon--collapsed'
					}
				/>
			</button>

			{expanded ? (
				<div className='task-attachments task-attachments--preview'>
					<div className='task-attachments-scroll'>
						{loading ? (
							<Group justify='center' py='sm'>
								<Loader size='sm' />
							</Group>
						) : events.length === 0 ? (
							<Text size='sm' c='dimmed'>
								No history yet.
							</Text>
						) : (
							<ol className='task-history-list'>
								{events.map((event) => {
									const body = eventBody(event);
									return (
										<li key={event.id} className='task-history-item'>
											<div className='task-history-item-marker' aria-hidden />
											<div className='task-history-item-content'>
												<p className='task-history-item-title'>
													{eventTitle(event)}
												</p>
												{body ? (
													<p className='task-history-item-detail'>{body}</p>
												) : null}
												<p className='task-history-item-when'>
													<RelativeTime
														value={event.at}
														variant='absolute'
													/>
												</p>
											</div>
										</li>
									);
								})}
							</ol>
						)}
					</div>
				</div>
			) : null}
		</section>
	);
}
