/**
 * Fictional sample rows for bulk import CSV downloads (10 per entity).
 */

/** @type {Record<string, string>[]} */
export const SAMPLE_CONTACT_ROWS = [
	{
		name: 'Alex Rivera',
		title: 'Site coordinator',
		phone: '555-0101',
		email: 'alex.rivera@example.com',
	},
	{
		name: 'Jordan Kim',
		title: 'Operations lead',
		phone: '555-0102',
		email: 'jordan.kim@example.com',
	},
	{
		name: 'Sam Patel',
		title: '',
		phone: '555-0103',
		email: 'sam.patel@example.com',
	},
	{
		name: 'Casey Morgan',
		title: 'Venue contact',
		phone: '',
		email: 'casey.morgan@example.com',
	},
	{
		name: 'Riley Chen',
		title: 'Dispatcher',
		phone: '555-0105',
		email: '',
	},
	{
		name: 'Taylor Brooks',
		title: 'Account manager',
		phone: '555-0106',
		email: 'taylor.brooks@example.com',
	},
	{
		name: 'Morgan Lee',
		title: '',
		phone: '555-0107',
		email: 'morgan.lee@example.com',
	},
	{
		name: 'Jamie Ortiz',
		title: 'Crew lead',
		phone: '555-0108',
		email: 'jamie.ortiz@example.com',
	},
	{
		name: 'Drew Nguyen',
		title: 'Facilities',
		phone: '555-0109',
		email: 'drew.nguyen@example.com',
	},
	{
		name: 'Quinn Adams',
		title: 'Receiving',
		phone: '555-0110',
		email: 'quinn.adams@example.com',
	},
];

/** @type {Record<string, string>[]} */
export const SAMPLE_ADDRESS_ROWS = [
	{
		addressName: 'North Warehouse',
		street: '100 Industrial Blvd',
		city: 'Springfield',
		state: 'IL',
		postalCode: '62701',
		building: 'Bay 3',
		notes: 'Use loading dock on east side',
	},
	{
		addressName: 'Downtown Office',
		street: '42 Market Street',
		city: 'Boston',
		state: 'MA',
		postalCode: '02108',
		building: 'Suite 200',
		notes: '',
	},
	{
		addressName: 'Riverside Park',
		street: '800 River Road',
		city: 'Austin',
		state: 'TX',
		postalCode: '78701',
		building: '',
		notes: 'Gate code 4521',
	},
	{
		addressName: 'East Distribution',
		street: '15 Freight Lane',
		city: 'Columbus',
		state: 'OH',
		postalCode: '43215',
		building: 'Building B',
		notes: 'Call on arrival',
	},
	{
		addressName: 'Convention Center',
		street: '500 Expo Drive',
		city: 'Denver',
		state: 'CO',
		postalCode: '80202',
		building: 'Hall C',
		notes: 'Deliveries before 10am',
	},
	{
		addressName: 'Harbor Storage',
		street: '22 Pier Avenue',
		city: 'Seattle',
		state: 'WA',
		postalCode: '98101',
		building: '',
		notes: '',
	},
	{
		addressName: 'University Campus',
		street: '1 College Way',
		city: 'Ann Arbor',
		state: 'MI',
		postalCode: '48104',
		building: 'Arts building',
		notes: 'Student entrance only',
	},
	{
		addressName: 'Suburban Retail',
		street: '900 Shopping Center Dr',
		city: 'Phoenix',
		state: 'AZ',
		postalCode: '85004',
		building: 'Unit 12',
		notes: 'Rear entrance',
	},
	{
		addressName: 'Airport Cargo',
		street: 'Terminal Road',
		city: 'Atlanta',
		state: 'GA',
		postalCode: '30320',
		building: 'Cargo 4',
		notes: 'Badge required',
	},
	{
		addressName: 'Community Center',
		street: '77 Oak Street',
		city: 'Portland',
		state: 'OR',
		postalCode: '97201',
		building: '',
		notes: 'Weekend access via side gate',
	},
];

/** @type {Record<string, string | boolean>[]} */
export const SAMPLE_USER_ROWS = [
	{
		displayName: 'Alex Rivera',
		email: 'alex.rivera@example.com',
		phone: '555-0201',
		role: 'Coordinator',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: true,
	},
	{
		displayName: 'Jordan Kim',
		email: 'jordan.kim@example.com',
		phone: '555-0202',
		role: 'Admin',
		manageUsers: true,
		manageOrg: true,
		viewCrewMap: true,
	},
	{
		displayName: 'Sam Patel',
		email: 'sam.patel@example.com',
		phone: '555-0203',
		role: 'Crew',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: false,
	},
	{
		displayName: 'Casey Morgan',
		email: 'casey.morgan@example.com',
		phone: '',
		role: 'Crew',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: false,
	},
	{
		displayName: 'Riley Chen',
		email: 'riley.chen@example.com',
		phone: '555-0205',
		role: 'Dispatcher',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: true,
	},
	{
		displayName: 'Taylor Brooks',
		email: 'taylor.brooks@example.com',
		phone: '555-0206',
		role: 'Manager',
		manageUsers: true,
		manageOrg: false,
		viewCrewMap: true,
	},
	{
		displayName: 'Morgan Lee',
		email: 'morgan.lee@example.com',
		phone: '555-0207',
		role: 'Crew',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: false,
	},
	{
		displayName: 'Jamie Ortiz',
		email: 'jamie.ortiz@example.com',
		phone: '555-0208',
		role: 'Lead',
		manageUsers: false,
		manageOrg: true,
		viewCrewMap: true,
	},
	{
		displayName: 'Drew Nguyen',
		email: 'drew.nguyen@example.com',
		phone: '555-0209',
		role: 'Crew',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: false,
	},
	{
		displayName: 'Quinn Adams',
		email: 'quinn.adams@example.com',
		phone: '555-0210',
		role: 'Ops',
		manageUsers: false,
		manageOrg: false,
		viewCrewMap: true,
	},
];
